---
- name: Listen for events on a webhook
  hosts: localhost
  sources:
    - name: github-tag-webhook
      ansible.eda.webhook:
        port: 5000
        host: 0.0.0.0

  rules:
    - name: trigger-job-on-tag
      condition: event.payload.ref_type == "tag"
      action:
        run_job_template:
          name: "tag_created"
          organization: "Private Cloud Projects"
