- name: GitHub Tag Rulebook
  hosts: localhost
  sources:
    - ansible.eda.github:
        token: "{{ credential.token }}"
        repositories:
          - owner: hmalireddy1
            repo: eda-github-tags
        event_types:
          - create

  rules:
    - name: tag creation rule
      condition: event.payload.ref_type == "tag"
      action:
        run_playbook:
          name: playbooks/on_tag_created.yml
          inventory:
            hosts: localhost
